version: "3.9"

services:
  api-gateway:
    image: ghcr.io/azicussdu/api-gateway:latest
    container_name: api-gateway
    depends_on:
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
      order-service:
        condition: service_started
    environment:
      PORT: 8080
      USER_SERVICE_URL: http://user-service:8081
      ORDER_SERVICE_URL: http://order-service:8082
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      JWT_SECRET: super-secret-jwt-key
      INTERNAL_SERVICE_TOKEN: internal-service-token
      USER_CACHE_TTL: 10m
    ports:
      - "8080:8080"

  user-service:
    image: ghcr.io/azicussdu/user-service:latest
    container_name: user-service
    depends_on:
      postgres-user:
        condition: service_healthy
    environment:
      PORT: 8081
      DATABASE_DSN: host=postgres-user user=user_service password=user_service dbname=user_service port=5432 sslmode=disable TimeZone=UTC
      JWT_SECRET: super-secret-jwt-key
      INTERNAL_SERVICE_TOKEN: internal-service-token
    ports:
      - "8081:8081"

  order-service:
    image: ghcr.io/azicussdu/order-service:latest
    container_name: order-service
    depends_on:
      postgres-order:
        condition: service_healthy
    environment:
      PORT: 8082
      DATABASE_DSN: host=postgres-order user=order_service password=order_service dbname=order_service port=5432 sslmode=disable TimeZone=UTC
      INTERNAL_SERVICE_TOKEN: internal-service-token
    ports:
      - "8082:8082"

  postgres-user:
    image: postgres:16-alpine
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_service
      POSTGRES_USER: user_service
      POSTGRES_PASSWORD: user_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_service -d user_service"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5433:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data

  postgres-order:
    image: postgres:16-alpine
    container_name: postgres-order
    environment:
      POSTGRES_DB: order_service
      POSTGRES_USER: order_service
      POSTGRES_PASSWORD: order_service
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U order_service -d order_service"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5434:5432"
    volumes:
      - postgres-order-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: redis
    command: ["redis-server", "--appendonly", "yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-user-data:
  postgres-order-data:
  redis-data:
